Include <iterator>.
In order to fix:
[   16s] /home/abuild/rpmbuild/BUILD/libkleo-21.12.3/src/kleo/keyserverconfig.cpp:73:44:   required from here
[   16s] /home/abuild/rpmbuild/BUILD/libkleo-21.12.3/src/utils/algorithm.h:35:30: error: no matching function for call to 'begin(QStringList&)'
[   16s]    35 |     std::transform(std::begin(c), std::end(c), std::begin(c), op);
[   16s]       |                    ~~~~~~~~~~^~~

The change is documented here:
https://gcc.gnu.org/gcc-12/porting_to.html#header-dep-changes

(cherry picked from commit f290218a6fd4e2b849875f6d465eaa861ec02aff)