Fix compilation with GCC 7
mem_fn is part of functional, and GCC 7 requires an explicit include.

Otherwise:

/home/abuild/rpmbuild/build/libkleo-16.12.2/src/kleo/defaultkeyfilter.cpp:45:30: error: 'mem_fn' is not a member of 'std'